[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    vulnerability: Backend vulnerability security tests
    loadtest: Load and performance analysis tests

log_cli = true
log_cli_level = INFO
