// Mocks generated by Mockito 5.4.6 from annotations
// in flowpay_app/test/services/offline_transaction_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowpay_app/models/bank_account.dart' as _i8;
import 'package:flowpay_app/models/flowpay_notification.dart' as _i11;
import 'package:flowpay_app/models/offline_transaction.dart' as _i7;
import 'package:flowpay_app/models/payment_transaction.dart' as _i6;
import 'package:flowpay_app/models/wallet_transaction.dart' as _i5;
import 'package:flowpay_app/models/wallet_user.dart' as _i4;
import 'package:flowpay_app/services/notification_service.dart' as _i10;
import 'package:flowpay_app/services/wallet_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletService extends _i1.Mock implements _i2.WalletService {
  MockWalletService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUserWallet({
    required String? uid,
    required String? email,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWallet, [], {
              #uid: uid,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> ensureWalletExists({
    required String? uid,
    required String? email,
    String? phone = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ensureWalletExists, [], {
              #uid: uid,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserIdByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdByEmail, [email]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUserIdByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdByPhone, [phone]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Stream<_i4.WalletUser?> watchWallet(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchWallet, [uid]),
            returnValue: _i3.Stream<_i4.WalletUser?>.empty(),
          )
          as _i3.Stream<_i4.WalletUser?>);

  @override
  _i3.Stream<List<_i5.WalletTransaction>> watchTransactions(
    String? uid, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactions, [uid], {#limit: limit}),
            returnValue: _i3.Stream<List<_i5.WalletTransaction>>.empty(),
          )
          as _i3.Stream<List<_i5.WalletTransaction>>);

  @override
  _i3.Stream<int> watchOfflineSyncedCount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchOfflineSyncedCount, [uid]),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<List<_i6.PaymentTransaction>> watchPaymentTransactions(
    String? uid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaymentTransactions, [uid]),
            returnValue: _i3.Stream<List<_i6.PaymentTransaction>>.empty(),
          )
          as _i3.Stream<List<_i6.PaymentTransaction>>);

  @override
  _i3.Future<void> addMoney({required String? uid, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#addMoney, [], {#uid: uid, #amount: amount}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendMoney({
    required String? senderId,
    required String? senderPhone,
    required String? receiverId,
    required String? receiverPhone,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMoney, [], {
              #senderId: senderId,
              #senderPhone: senderPhone,
              #receiverId: receiverId,
              #receiverPhone: receiverPhone,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveSyncedOfflineTransaction(
    _i7.OfflineTransaction? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSyncedOfflineTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.BankAccount>> watchBankAccounts(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchBankAccounts, [uid]),
            returnValue: _i3.Stream<List<_i8.BankAccount>>.empty(),
          )
          as _i3.Stream<List<_i8.BankAccount>>);

  @override
  _i3.Stream<_i8.BankAccount?> watchPrimaryBankAccount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchPrimaryBankAccount, [uid]),
            returnValue: _i3.Stream<_i8.BankAccount?>.empty(),
          )
          as _i3.Stream<_i8.BankAccount?>);

  @override
  _i3.Stream<int> watchWithdrawalRequestsCount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchWithdrawalRequestsCount, [uid]),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> linkBankAccount({
    required String? uid,
    required String? bankName,
    required String? accountHolderName,
    required String? accountLast4,
    required String? ifscCode,
    required String? upiId,
    required bool? isPrimary,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkBankAccount, [], {
              #uid: uid,
              #bankName: bankName,
              #accountHolderName: accountHolderName,
              #accountLast4: accountLast4,
              #ifscCode: ifscCode,
              #upiId: upiId,
              #isPrimary: isPrimary,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unlinkBankAccount({
    required String? uid,
    required String? bankId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkBankAccount, [], {
              #uid: uid,
              #bankId: bankId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recordRazorpayTransaction({
    required String? uid,
    required double? amount,
    required String? status,
    String? razorpayPaymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordRazorpayTransaction, [], {
              #uid: uid,
              #amount: amount,
              #status: status,
              #razorpayPaymentId: razorpayPaymentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> submitWithdrawalRequest({
    required String? uid,
    required String? userName,
    required String? bankId,
    required String? bankName,
    required String? accountLast4,
    required String? accountHolderName,
    required String? ifscCode,
    required String? upiId,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitWithdrawalRequest, [], {
              #uid: uid,
              #userName: userName,
              #bankId: bankId,
              #bankName: bankName,
              #accountLast4: accountLast4,
              #accountHolderName: accountHolderName,
              #ifscCode: ifscCode,
              #upiId: upiId,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBankAccount({
    required String? uid,
    required String? bankId,
    required String? bankName,
    required String? accountHolderName,
    required String? accountLast4,
    required String? ifscCode,
    required String? upiId,
    required bool? isPrimary,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBankAccount, [], {
              #uid: uid,
              #bankId: bankId,
              #bankName: bankName,
              #accountHolderName: accountHolderName,
              #accountLast4: accountLast4,
              #ifscCode: ifscCode,
              #upiId: upiId,
              #isPrimary: isPrimary,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPrimaryBankAccount({
    required String? uid,
    required String? bankId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryBankAccount, [], {
              #uid: uid,
              #bankId: bankId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String hashPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#hashPin, [pin]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#hashPin, [pin]),
            ),
          )
          as String);

  @override
  _i3.Future<void> setWalletPin(String? uid, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setWalletPin, [uid, pin]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> verifyWalletPin(String? uid, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyWalletPin, [uid, pin]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateWithdrawalStatus({
    required String? withdrawalId,
    required String? uid,
    required double? amount,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWithdrawalStatus, [], {
              #withdrawalId: withdrawalId,
              #uid: uid,
              #amount: amount,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> transferWalletToBank({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transferWalletToBank, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> transferBankToWallet({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transferBankToWallet, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i10.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> notifyMoneyAdded({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyMoneyAdded, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyTransferToBank({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyTransferToBank, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyTransferFromBank({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyTransferFromBank, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPaymentSent({
    required String? senderId,
    required double? amount,
    required String? receiverPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPaymentSent, [], {
              #senderId: senderId,
              #amount: amount,
              #receiverPhone: receiverPhone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPaymentReceived({
    required String? receiverId,
    required double? amount,
    required String? senderPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPaymentReceived, [], {
              #receiverId: receiverId,
              #amount: amount,
              #senderPhone: senderPhone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyOfflineSyncCompleted({required String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#notifyOfflineSyncCompleted, [], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyRazorpaySuccess({
    required String? uid,
    required double? amount,
    required String? paymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRazorpaySuccess, [], {
              #uid: uid,
              #amount: amount,
              #paymentId: paymentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyRazorpayFailure({
    required String? uid,
    required double? amount,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRazorpayFailure, [], {
              #uid: uid,
              #amount: amount,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyBankLinked({
    required String? uid,
    required String? bankName,
    required String? last4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBankLinked, [], {
              #uid: uid,
              #bankName: bankName,
              #last4: last4,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyBankUpdated({
    required String? uid,
    required String? bankName,
    required String? last4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBankUpdated, [], {
              #uid: uid,
              #bankName: bankName,
              #last4: last4,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalSubmitted({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalSubmitted, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalApproved({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalApproved, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalRejected({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalRejected, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i11.FlowPayNotification>> watchNotifications(
    String? uid, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [uid], {#limit: limit}),
            returnValue: _i3.Stream<List<_i11.FlowPayNotification>>.empty(),
          )
          as _i3.Stream<List<_i11.FlowPayNotification>>);

  @override
  _i3.Stream<int> watchUnreadCount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, [uid]),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> markAsRead({
    required String? uid,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #uid: uid,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
