// Mocks generated by Mockito 5.4.6 from annotations
// in flowpay_app/test/services/wallet_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowpay_app/models/flowpay_notification.dart' as _i4;
import 'package:flowpay_app/services/email_service.dart' as _i5;
import 'package:flowpay_app/services/notification_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i2.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> notifyMoneyAdded({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyMoneyAdded, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyTransferToBank({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyTransferToBank, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyTransferFromBank({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyTransferFromBank, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPaymentSent({
    required String? senderId,
    required double? amount,
    required String? receiverPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPaymentSent, [], {
              #senderId: senderId,
              #amount: amount,
              #receiverPhone: receiverPhone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyPaymentReceived({
    required String? receiverId,
    required double? amount,
    required String? senderPhone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyPaymentReceived, [], {
              #receiverId: receiverId,
              #amount: amount,
              #senderPhone: senderPhone,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyOfflineSyncCompleted({required String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#notifyOfflineSyncCompleted, [], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyRazorpaySuccess({
    required String? uid,
    required double? amount,
    required String? paymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRazorpaySuccess, [], {
              #uid: uid,
              #amount: amount,
              #paymentId: paymentId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyRazorpayFailure({
    required String? uid,
    required double? amount,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyRazorpayFailure, [], {
              #uid: uid,
              #amount: amount,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyBankLinked({
    required String? uid,
    required String? bankName,
    required String? last4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBankLinked, [], {
              #uid: uid,
              #bankName: bankName,
              #last4: last4,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyBankUpdated({
    required String? uid,
    required String? bankName,
    required String? last4,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyBankUpdated, [], {
              #uid: uid,
              #bankName: bankName,
              #last4: last4,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalSubmitted({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalSubmitted, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalApproved({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalApproved, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyWithdrawalRejected({
    required String? uid,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyWithdrawalRejected, [], {
              #uid: uid,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.FlowPayNotification>> watchNotifications(
    String? uid, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [uid], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.FlowPayNotification>>.empty(),
          )
          as _i3.Stream<List<_i4.FlowPayNotification>>);

  @override
  _i3.Stream<int> watchUnreadCount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, [uid]),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> markAsRead({
    required String? uid,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #uid: uid,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [EmailService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailService extends _i1.Mock implements _i5.EmailService {
  MockEmailService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendPaymentSentEmail({
    required String? toEmail,
    required String? userName,
    required String? amount,
    required String? receiverPhone,
    required String? transactionId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPaymentSentEmail, [], {
              #toEmail: toEmail,
              #userName: userName,
              #amount: amount,
              #receiverPhone: receiverPhone,
              #transactionId: transactionId,
              #timestamp: timestamp,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendPaymentReceivedEmail({
    required String? toEmail,
    required String? userName,
    required String? amount,
    required String? senderPhone,
    required String? transactionId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPaymentReceivedEmail, [], {
              #toEmail: toEmail,
              #userName: userName,
              #amount: amount,
              #senderPhone: senderPhone,
              #transactionId: transactionId,
              #timestamp: timestamp,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendWithdrawalSubmittedEmail({
    required String? toEmail,
    required String? userName,
    required String? amount,
    required String? bankName,
    required String? accountLast4,
    required String? upiId,
    required String? withdrawalId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendWithdrawalSubmittedEmail, [], {
              #toEmail: toEmail,
              #userName: userName,
              #amount: amount,
              #bankName: bankName,
              #accountLast4: accountLast4,
              #upiId: upiId,
              #withdrawalId: withdrawalId,
              #timestamp: timestamp,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendWithdrawalApprovedEmail({
    required String? toEmail,
    required String? userName,
    required String? amount,
    required String? bankName,
    required String? accountLast4,
    required String? upiId,
    required String? withdrawalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendWithdrawalApprovedEmail, [], {
              #toEmail: toEmail,
              #userName: userName,
              #amount: amount,
              #bankName: bankName,
              #accountLast4: accountLast4,
              #upiId: upiId,
              #withdrawalId: withdrawalId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendWithdrawalRejectedEmail({
    required String? toEmail,
    required String? userName,
    required String? amount,
    required String? bankName,
    required String? accountLast4,
    required String? withdrawalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendWithdrawalRejectedEmail, [], {
              #toEmail: toEmail,
              #userName: userName,
              #amount: amount,
              #bankName: bankName,
              #accountLast4: accountLast4,
              #withdrawalId: withdrawalId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
